# -*- coding: utf-8 -*-
"""Data Synthetic Generator 165 variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uNPdXst3VX4Y24aBpCZFsabFQmHOD0S
"""

import numpy as np
import pandas as pd
from sklearn.datasets import make_spd_matrix
from factor_analyzer.factor_analyzer import calculate_kmo


# Variables as provided
variables = [
    "Average cost per IoT sensor unit deployed",
    "Number of datasets managed using open-source platforms",
    "Percentage of total data collected via mobile applications",
    "Number of data points contributed by community members",
    "Number of active collaborations or data-sharing agreements",
    "Number of satellite datasets integrated into urban systems",
    "Reduction in local hardware costs due to cloud-based AI adoption",
    "Percentage reduction in required training data due to transfer learning",
    "Number of AI tools/frameworks downloaded or adopted",
    "Number of AI projects developed in collaboration with other cities",
    "Accuracy of NLP models in local language text processing",
    "Number of participants completing AI training programs",
    "Number of user interactions with climate education chatbots",
    "Number of app users completing sustainability challenges",
    "Number of community-led action plans submitted through the tool",
    "Number of queries handled by voice-based climate services",
    "Percentage of funds allocated based on participatory input",
    "Number of schools implementing the curriculum",
    "Average internet speed in the target area",
    "Average latency in transmitting data across networks",
    "Number of processes executed via cloud platforms",
    "Total storage capacity available in local data centers",
    "Number of computational nodes available for urban applications",
    "Number of software licenses/tools actively in use",
    "Number of training sessions conducted annually",
    "Number of participants in community engagement activities",
    "Frequency of scheduled maintenance for systems",
    "Percentage reduction in resource consumption through sustainable practices",
    "Percentage of renewable energy usage within the microgrid",
    "Reduction in unplanned outages due to predictive maintenance",
    "Percentage of households with retrofitted smart meters installed",
    "Solar energy generation efficiency improvement",
    "Percentage reduction in household energy consumption after app usage",
    "Increase in energy efficiency due to grid optimization",
    "Reduction in average commute times for transit users",
    "Reduction in traffic congestion levels",
    "Increase in usage of bike-sharing and walking paths",
    "Number of shared trips coordinated through AI platforms",
    "Percentage of EVs integrated into the urban grid infrastructure",
    "User retention rate for waste sorting apps",
    "Reduction in fuel consumption for waste collection vehicles",
    "Accuracy of recycling material detection using AI",
    "Increase in compost production efficiency",
    "Number of circular economy initiatives identified and implemented",
    "Number of zoning changes implemented based on AI recommendations",
    "Increase in green space coverage due to optimized placement",
    "Number of upgraded informal settlements based on AI strategies",
    "Accuracy of flood risk prediction models",
    "Temperature reduction in targeted urban heat island areas",
    "Time taken to detect and fix leaks in water systems",
    "Increase in water access points due to optimized kiosk placement",
    "Number of water quality parameters monitored in real-time",
    "Increase in water harvested per rainfall event",
    "Accuracy of drought prediction models",
    "Number of air quality monitoring stations established",
    "Reduction in air pollution levels in identified hotspots",
    "Percentage of households adopting clean cooking technologies",
    "Reduction in air pollution due to urban greening efforts",
    "Reduction in energy usage in buildings using smart thermostats",
    "Percentage improvement in ventilation efficiency for buildings",
    "Energy savings achieved through AI-driven behavior interventions",
    "Number of housing units retrofitted based on AI prioritization",
    "Number of buildings audited using smartphone technology",
    "Accuracy of ML models in solving specific tasks",
    "Number of IoT devices deployed",
    "Number of GIS layers used in urban planning",
    "Language processing accuracy for low-resource languages",
    "Accuracy of object detection in real-world applications",
    "Accuracy of predicted vs actual crop yields",
    "Percentage increase in crop yield due to precision techniques",
    "Reduction in pest damage through AI-based detection",
    "Percentage of livestock health issues detected early using IoT",
    "Accuracy of market price prediction models",
    "Reduction in response time to disasters",
    "Number of risks identified and mitigated using AI",
    "Increase in efficiency of disaster response resources",
    "Reduction in assessment time after disasters",
    "Number of community members trained through AI simulations",
    "Reduction in crime rates in targeted areas",
    "Number of threats detected and mitigated in real time",
    "Reduction in traffic accidents in managed areas",
    "Reduction in crowd-related incidents during events",
    "Number of security breaches prevented",
    "Accuracy of outbreak predictions made by AI systems",
    "Percentage of accurate diagnoses made using AI systems",
    "Improvement in patient outcomes due to personalized plans",
    "Number of patients treated via AI-enabled telemedicine",
    "Reduction in resource wastage in healthcare systems",
    "Improvement in student learning outcomes due to personalization",
    "Number of tutoring sessions conducted via AI systems",
    "Number of educational materials created and delivered using AI",
    "Reduction in identified learning gaps through data-driven interventions",
    "Number of individuals trained in AI and emerging technologies",
    "Percentage of population reached by early warning systems",
    "Reduction in response time for disaster relief efforts",
    "Number of critical structures monitored using low-cost sensors",
    "Number of participants trained in disaster preparedness",
    "Time taken to complete needs assessment after a disaster",
    "Number of vulnerabilities identified through mapping efforts",
    "Reduction in heat wave-related incidents in vulnerable areas",
    "Accuracy of disease prediction models",
    "Number of disease outbreaks detected through surveillance systems",
    "Percentage of population with access to green spaces within 500 meters",
    "Reduction in indoor air pollutant levels",
    "Number of individuals employed in green jobs post-training",
    "Number of microenterprises established for climate-related solutions",
    "Number of successful job placements through AI-assisted matching",
    "Increase in household income stability in vulnerable areas",
    "Increase in yield per square meter of urban farming",
    "Number of community gardens established in optimized locations",
    "Percentage of food surplus redistributed through the platform",
    "Yield improvement for small-scale farmers using precision techniques",
    "Reduction in inequities identified through policy assessments",
    "Number of decisions with documented transparency and fairness",
    "Time saved in generating climate action reports",
    "Number of collaborative projects initiated through the platform",
    "Number of ethical guidelines integrated into AI projects",
    "Number of insights generated from analyzed literature",
    "Number of microfinance loans approved for green projects",
    "Accuracy of finance need predictions for climate initiatives",
    "Percentage increase in funds raised for local climate projects",
    "Number of green bond projects with documented impact reports",
    "Success rate of funding proposals generated with AI assistance",
    "Number of kits distributed and utilized by local innovators",
    "Number of successful matches for innovation challenges",
    "Number of startups supported through virtual incubation",
    "Number of innovations documented in the repository",
    "Number of successful skill-sharing interactions on the platform",
    "Number of projects ranked using the prioritisation matrix",
    "Percentage improvement in performance after iterative cycles",
    "Number of additional locations where the solution has been implemented",
    "Number of officials trained in AI and climate-related skills",
    "Number of workshops conducted annually",
    "Number of collaborative projects with educational institutions",
    "Percentage of data compliant with privacy regulations",
    "Number of decisions with publicly accessible AI decision logs",
    "Percentage of stakeholders represented in the design process",
    "Number of data-sharing agreements adhering to ownership policies",
    "Frequency of data collection intervals for monitoring",
    "Number of active communication channels maintained",
    "Storage capacity utilized for project data",
    "Number of skilled personnel trained and retained",
    "Time taken from AI development to deployment in applications",
    "Frequency of scheduled maintenance activities",
    "Number of impact assessments completed using AI tools",
    "Number of real-time dashboards actively monitored",
    "Number of actionable suggestions collected from community feedback",
    "Number of environmental parameters monitored",
    "Accuracy of sentiment analysis on public opinions regarding climate actions",
    "Number of urban metrics tracked (air quality)",
    "Number of visualizations created for decision-making processes",
    "Number of adaptive management strategies successfully implemented",
    "Number of scenarios analyzed to inform decision-making",
    "Number of variables assessed for sensitivity impact on outcomes",
    "Accuracy of model predictions across different climate scenarios",
    "Number of policy scenarios evaluated for effectiveness",
    "Number of alternative resource plans developed",
    "Level of community participation in different engagement models",
    "Percentage of stakeholders adopting proposed technologies",
    "Cost savings identified relative to implementation expenses",
    "Number of social indicators improved through interventions",
    "Reduction in environmental degradation metrics (CO2 levels)",
    "Number of technology solutions evaluated for feasibility",
    "Number of policies reviewed and updated based on evaluation outcomes",
    "Number of risks identified and mitigated in project implementation"
]

# Generate synthetic data
np.random.seed(42)
data_size = 300  # Number of samples
cov_matrix = make_spd_matrix(len(variables), random_state=42)  # Generate a positive-definite covariance matrix
mean_vector = np.random.uniform(0, 1, len(variables)) * 10  # Mean values for each variable
data = np.random.multivariate_normal(mean=mean_vector, cov=cov_matrix, size=data_size)

# Convert to DataFrame
df = pd.DataFrame(data, columns=variables)

# Calculate KMO to ensure suitability for factor analysis
kmo_all, kmo_model = calculate_kmo(df)

# Check KMO and adjust if necessary
if kmo_model < 0.8:
    while kmo_model < 0.8:
        df += np.random.normal(0, 0.1, df.shape)  # Add noise to adjust correlations
        kmo_all, kmo_model = calculate_kmo(df)

# Display the dataset and KMO result
#tools.display_dataframe_to_user(name="Synthetic Data for Factor Analysis", dataframe=df)
kmo_model
df

df.to_csv('KMO_165_vars.csv', index=False)

! pip install factor_analyzer